"""The chat list, and the transcript behind each entry in it.

Nothing here touches the query pipeline. It manages the conversations; asking a
question inside one goes through /api/query, which reads and appends via the
same store.

STATUS CODES
------------
The store raises three distinguishable things and they must not collapse into a
single 500, because they call for different responses from the client:

  ChatNotFound   -> 404. The chat is gone. Expected: concurrent chats mean one
                   can be deleted from the sidebar while another tab has it open.
                   The client drops it from the list.
  ChatStoreError -> 500. Misconfiguration — app_db pointed at the queryable
                   schema, or the read-only account given write credentials.
                   Retrying cannot help; someone has to fix .env.
  pymysql.Error  -> 503. MySQL is down or unreachable. Retrying is exactly the
                   right thing to do, and 503 is what says so.

The store deliberately does not fail soft (see services/chat_store.py). A write
that quietly vanishes loses a conversation the user can still see on screen, and
they find out on reload — so every failure surfaces here as a status code.
"""

import logging

import pymysql
from fastapi import APIRouter, HTTPException, Query

from app.models import (
    ChatDetailResponse,
    ChatListResponse,
    ChatModel,
    ChatTurnModel,
    CreateChatRequest,
    RenameChatRequest,
)
from app.services import chat_store
from app.services.chat_store import ChatNotFound, ChatStoreError

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/chats", tags=["chats"])


def _fail(exc: Exception) -> HTTPException:
    """Map a store failure onto the status code that describes it."""
    if isinstance(exc, ChatStoreError):
        logger.error("Chat store is misconfigured: %s", exc)
        return HTTPException(status_code=500, detail=str(exc))
    if isinstance(exc, pymysql.Error):
        logger.warning("Chat store unreachable: %s", exc)
        return HTTPException(
            status_code=503,
            detail="لا يمكن الوصول إلى مخزن المحادثات. حاول مرة أخرى.",
        )
    raise exc


@router.get("", response_model=ChatListResponse)
async def list_chats(limit: int = Query(chat_store.DEFAULT_CHAT_LIMIT, ge=1, le=1000)) -> ChatListResponse:
    """Chats by last activity, newest first.

    Sorted by updated_at rather than created_at so the conversation you were just
    in is at the top. A rename does not count as activity and does not reorder the
    list — see chat_store._rename_chat_sync.
    """
    try:
        chats = await chat_store.list_chats(limit=limit)
    except (ChatStoreError, pymysql.Error) as exc:
        raise _fail(exc) from exc
    return ChatListResponse(chats=[ChatModel(**chat) for chat in chats])


@router.post("", response_model=ChatModel, status_code=201)
async def create_chat(request: CreateChatRequest) -> ChatModel:
    """Start a conversation, or adopt the client-generated id of one.

    201 even when the id already existed. The request asked for a chat with that
    id to exist and it does; distinguishing "I made it" from "it was already
    there" would give the client a difference it has no use for.
    """
    try:
        chat = await chat_store.create_chat(request.id)
    except (ChatStoreError, pymysql.Error) as exc:
        raise _fail(exc) from exc
    return ChatModel(**chat)


@router.get("/{chat_id}", response_model=ChatDetailResponse)
async def get_chat(chat_id: str) -> ChatDetailResponse:
    """One chat with its transcript.

    Both in a single response because they are always wanted together: opening a
    chat means drawing it.

    Capped at CONTEXT_MAX_TURNS, the same rail replay uses. That is a ceiling in
    the hundreds and no real transcript reaches it — a chat runs out of context
    window long before it runs out of rows — so it bounds a pathological read
    without truncating an honest one.
    """
    try:
        chat = await chat_store.get_chat(chat_id)
        if chat is None:
            raise HTTPException(status_code=404, detail="لا توجد محادثة بهذا المعرّف.")
        turns = await chat_store.load_history(chat_id)
    except (ChatStoreError, pymysql.Error) as exc:
        raise _fail(exc) from exc
    return ChatDetailResponse(
        chat=ChatModel(**chat),
        turns=[ChatTurnModel(**turn) for turn in turns],
    )


@router.patch("/{chat_id}", response_model=ChatModel)
async def rename_chat(chat_id: str, request: RenameChatRequest) -> ChatModel:
    """Retitle a chat.

    Titles are otherwise generated by truncating the first question, which is a
    reasonable default and often a poor name. This is the correction.
    """
    try:
        chat = await chat_store.rename_chat(chat_id, request.title)
    except ChatNotFound as exc:
        raise HTTPException(status_code=404, detail="لا توجد محادثة بهذا المعرّف.") from exc
    except (ChatStoreError, pymysql.Error) as exc:
        raise _fail(exc) from exc
    return ChatModel(**chat)


@router.delete("/{chat_id}")
async def delete_chat(chat_id: str) -> dict:
    """Delete a chat and its transcript.

    Irreversible, and deliberately so — see db/07_app_schema.sql. A turn already
    in flight for this chat will fail with ChatNotFound when it tries to save,
    which is the correct outcome: the user asked for the conversation to be gone.
    """
    try:
        deleted = await chat_store.delete_chat(chat_id)
    except (ChatStoreError, pymysql.Error) as exc:
        raise _fail(exc) from exc
    if not deleted:
        raise HTTPException(status_code=404, detail="لا توجد محادثة بهذا المعرّف.")
    return {"deleted": chat_id}
