"""Chat conversations and their turns, kept in MySQL.

Until now the backend held no conversation state at all: the browser owned the
transcript and replayed it with every question. That works for one chat and
breaks for several — the transcript has to outlive the tab for a chat list to
mean anything, and two chats streaming at once cannot both be "the transcript".

WHAT THIS IS NOT
----------------
It is not the read path's connection. `services/db.py` connects as the SELECT-only
user and executes model-generated SQL; this module connects as a second account
with DML on `app_db` and nothing else, and every statement it runs is written by
hand below and fully parameterized. The two must not be merged, and the reason is
in db/07_app_schema.sql: the guard against a hallucinated `DROP` is that the
account running it physically cannot write, and that guarantee ends the moment
one connection does both jobs.

_assert_isolated() enforces the half of that which config can get wrong.

THE CONTEXT WINDOW IS NOT STORED
--------------------------------
No row here records how full a conversation is. `services/context.py` costs the
prompt from the turns it is handed, so each chat's budget is derived from that
chat's rows on every request. Storing a running total would add a number that can
disagree with the transcript it summarizes; deriving it cannot.

FAILURE POLICY
--------------
Unlike the query cache, this does NOT fail soft. A Redis that is down costs
seconds; a chat store that silently swallows writes loses the user's
conversation while showing it on screen, and they find out on reload. Every
function here raises, and callers decide what to tell the user.
"""

import json
import logging
import uuid
from datetime import datetime, timezone

import pymysql
import pymysql.cursors
from fastapi.concurrency import run_in_threadpool

from app.config import (
    APP_MYSQL_DATABASE,
    APP_MYSQL_HOST,
    APP_MYSQL_PASSWORD,
    APP_MYSQL_PORT,
    APP_MYSQL_USER,
    CONTEXT_MAX_TURNS,
    MYSQL_DATABASE,
    MYSQL_USER,
)

logger = logging.getLogger(__name__)

# Matches VARCHAR(255) in db/07_app_schema.sql, with room to spare: a title is
# generated by truncating the first question, and a question can be 2000 chars.
# Cutting well short of the column width means a title is never rejected for
# length, and never silently truncated by MySQL either.
TITLE_MAX_CHARS = 120

# How many chats the sidebar asks for. A ceiling on the list query, not a limit
# on how many chats may exist.
DEFAULT_CHAT_LIMIT = 200


class ChatStoreError(Exception):
    """Configuration or connection problem that makes the store unusable."""


class ChatNotFound(Exception):
    """The chat does not exist — usually deleted while a turn was in flight.

    A real case now that chats can stream concurrently: the user can delete a
    conversation from the sidebar while its answer is still being written. The
    foreign key rejects the orphaned turn, and this is that rejection told
    apart from a genuine database failure.
    """


def _assert_isolated() -> None:
    """Refuse to run if this connection is pointed at the queryable schema.

    db/07_app_schema.sql keeps transcripts out of `legal_db` so that neither
    Debezium nor a model-generated SELECT can reach them. That separation is
    configuration, and configuration can be edited — an `.env` with
    APP_MYSQL_DATABASE=legal_db reinstates exactly the problem the separate
    schema exists to prevent, and nothing would complain. This complains.
    """
    if APP_MYSQL_DATABASE == MYSQL_DATABASE:
        raise ChatStoreError(
            f"APP_MYSQL_DATABASE is {APP_MYSQL_DATABASE!r}, the same schema the query "
            "pipeline reads. Chat transcripts stored there become documentable by CDC "
            "and readable by model-generated SQL. See db/07_app_schema.sql."
        )
    if APP_MYSQL_USER == MYSQL_USER:
        raise ChatStoreError(
            f"APP_MYSQL_USER is {APP_MYSQL_USER!r}, the same account that executes "
            "model-generated SQL. That account must stay SELECT-only. "
            "See db/03_readonly_user.sql."
        )


def _connect() -> pymysql.connections.Connection:
    _assert_isolated()
    return pymysql.connect(
        host=APP_MYSQL_HOST,
        port=APP_MYSQL_PORT,
        user=APP_MYSQL_USER,
        password=APP_MYSQL_PASSWORD,
        database=APP_MYSQL_DATABASE,
        cursorclass=pymysql.cursors.DictCursor,
        # Off, unlike db.py: append_turn writes a turn and bumps the chat's
        # updated_at, and a chat whose timestamp disagrees with its newest turn
        # sorts wrongly in the sidebar forever. Each function below commits once.
        autocommit=False,
        connect_timeout=5,
        read_timeout=10,
    )


def _now() -> datetime:
    """UTC, naive — MySQL DATETIME carries no zone, so the zone is a convention.

    Stored naive-UTC and converted back to an epoch float on read, so callers
    never see a value whose zone depends on where the server runs.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _epoch(value: datetime | None) -> float:
    """A stored DATETIME as an epoch float, matching the rest of the API."""
    if value is None:
        return 0.0
    return value.replace(tzinfo=timezone.utc).timestamp()


def _title_from(question: str) -> str:
    """A chat's name, taken from the question that started it.

    Deliberately not model-generated. A title is worth one line of string
    handling; it is not worth a completion call, several seconds, and a second
    thing that can fail before the user sees their first answer.
    """
    collapsed = " ".join(question.split())
    if len(collapsed) <= TITLE_MAX_CHARS:
        return collapsed
    return collapsed[: TITLE_MAX_CHARS - 1].rstrip() + "…"


def _row_to_chat(row: dict) -> dict:
    return {
        "id": row["id"],
        "title": row["title"],
        "created_at": _epoch(row["created_at"]),
        "updated_at": _epoch(row["updated_at"]),
        "turn_count": int(row.get("turn_count") or 0),
    }


def _row_to_turn(row: dict) -> dict:
    """One stored turn, in HistoryTurn's field names.

    `sql_text` becomes `sql` here — the column is renamed only because `sql` is
    a MySQL reserved word (db/07_app_schema.sql). Callers build HistoryTurn
    straight from this.
    """
    raw = row["table_names"]
    # PyMySQL hands back a JSON column as a string on some server/driver
    # combinations and as a parsed list on others. Accept both rather than
    # depending on which.
    if isinstance(raw, str):
        try:
            names = json.loads(raw)
        except json.JSONDecodeError:
            logger.warning("Turn %s has unparseable table_names; treating as empty", row["id"])
            names = []
    else:
        names = raw
    return {
        "id": row["id"],
        "question": row["question"],
        "sql": row["sql_text"],
        "answer": row["answer"],
        "table_names": names if isinstance(names, list) else [],
        "created_at": _epoch(row["created_at"]),
    }


# --- Synchronous bodies -------------------------------------------------------
# Each opens a connection, does its work in one transaction, and closes it —
# the same per-call pattern as services/db.py. Chat traffic is one statement per
# user action, so a pool would add a lifecycle to manage for no measured gain.


def _create_chat_sync(chat_id: str | None) -> dict:
    chat_id = chat_id or str(uuid.uuid4())
    now = _now()
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            # Idempotent: the browser generates the id and may retry the create
            # after a dropped connection. A retry must not be an error, and must
            # not reset the timestamps of a chat that already has turns.
            cursor.execute(
                "INSERT INTO chats (id, title, created_at, updated_at) "
                "VALUES (%s, NULL, %s, %s) "
                "ON DUPLICATE KEY UPDATE id = id",
                (chat_id, now, now),
            )
            # The turn count is selected even though a freshly created chat has
            # none: this call is idempotent, so it can just as easily be
            # returning an existing conversation with a transcript. Defaulting
            # to 0 here would report an empty chat to a sidebar that is about to
            # draw it.
            cursor.execute(
                "SELECT c.id, c.title, c.created_at, c.updated_at, "
                "       (SELECT COUNT(*) FROM turns t WHERE t.chat_id = c.id) AS turn_count "
                "  FROM chats c WHERE c.id = %s",
                (chat_id,),
            )
            row = cursor.fetchone()
        connection.commit()
    finally:
        connection.close()
    return _row_to_chat(row)


def _list_chats_sync(limit: int) -> list[dict]:
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            # LEFT JOIN, not INNER: a chat with no turns yet is the one the user
            # is looking at right now, and it has to appear in the list.
            cursor.execute(
                "SELECT c.id, c.title, c.created_at, c.updated_at, "
                "       COUNT(t.id) AS turn_count "
                "  FROM chats c "
                "  LEFT JOIN turns t ON t.chat_id = c.id "
                " GROUP BY c.id, c.title, c.created_at, c.updated_at "
                " ORDER BY c.updated_at DESC "
                " LIMIT %s",
                (limit,),
            )
            rows = cursor.fetchall()
        connection.commit()
    finally:
        connection.close()
    return [_row_to_chat(row) for row in rows]


def _get_chat_sync(chat_id: str) -> dict | None:
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT c.id, c.title, c.created_at, c.updated_at, "
                "       (SELECT COUNT(*) FROM turns t WHERE t.chat_id = c.id) AS turn_count "
                "  FROM chats c WHERE c.id = %s",
                (chat_id,),
            )
            row = cursor.fetchone()
        connection.commit()
    finally:
        connection.close()
    return _row_to_chat(row) if row else None


def _rename_chat_sync(chat_id: str, title: str) -> dict:
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            # updated_at is deliberately NOT bumped. It is the sidebar's "last
            # activity" sort key, and renaming a chat is not activity in it —
            # bumping it would jump an old conversation to the top for a typo fix.
            cursor.execute(
                "UPDATE chats SET title = %s WHERE id = %s",
                (title[:TITLE_MAX_CHARS], chat_id),
            )
            if cursor.rowcount == 0:
                # rowcount is 0 both for a missing chat and for a rename to the
                # identical title, so check existence rather than assume.
                cursor.execute("SELECT 1 FROM chats WHERE id = %s", (chat_id,))
                if cursor.fetchone() is None:
                    connection.rollback()
                    raise ChatNotFound(chat_id)
            cursor.execute(
                "SELECT c.id, c.title, c.created_at, c.updated_at, "
                "       (SELECT COUNT(*) FROM turns t WHERE t.chat_id = c.id) AS turn_count "
                "  FROM chats c WHERE c.id = %s",
                (chat_id,),
            )
            row = cursor.fetchone()
        connection.commit()
    finally:
        connection.close()
    return _row_to_chat(row)


def _delete_chat_sync(chat_id: str) -> bool:
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            # The turns go with it, via ON DELETE CASCADE.
            cursor.execute("DELETE FROM chats WHERE id = %s", (chat_id,))
            deleted = cursor.rowcount > 0
        connection.commit()
    finally:
        connection.close()
    return deleted


def _append_turn_sync(
    chat_id: str,
    question: str,
    sql: str,
    answer: str,
    table_names: list[str],
) -> dict:
    now = _now()
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            try:
                cursor.execute(
                    "INSERT INTO turns "
                    "  (chat_id, question, sql_text, answer, table_names, created_at) "
                    "VALUES (%s, %s, %s, %s, %s, %s)",
                    (chat_id, question, sql, answer, json.dumps(table_names, ensure_ascii=False), now),
                )
            except pymysql.IntegrityError as exc:
                # 1452: foreign key violation — the chat was deleted while this
                # answer was being written. Expected under concurrent chats, and
                # not a server fault.
                connection.rollback()
                if exc.args and exc.args[0] == 1452:
                    raise ChatNotFound(chat_id) from exc
                raise
            turn_id = cursor.lastrowid

            # COALESCE names the chat from its first question and leaves every
            # later turn alone — including a title the user has since edited.
            cursor.execute(
                "UPDATE chats SET title = COALESCE(title, %s), updated_at = %s WHERE id = %s",
                (_title_from(question), now, chat_id),
            )
        connection.commit()
    finally:
        connection.close()
    return {
        "id": turn_id,
        "question": question,
        "sql": sql,
        "answer": answer,
        "table_names": table_names,
        "created_at": _epoch(now),
    }


def _load_history_sync(chat_id: str, limit: int) -> list[dict]:
    connection = _connect()
    try:
        with connection.cursor() as cursor:
            # Newest-first with a LIMIT, then reversed, so a long conversation
            # reads only the turns that can still fit rather than all of them.
            # `id` ascending is insertion order, so this needs no created_at sort.
            cursor.execute(
                "SELECT id, question, sql_text, answer, table_names, created_at "
                "  FROM turns WHERE chat_id = %s "
                " ORDER BY id DESC LIMIT %s",
                (chat_id, limit),
            )
            rows = cursor.fetchall()
        connection.commit()
    finally:
        connection.close()
    return [_row_to_turn(row) for row in reversed(rows)]


# --- Async API ----------------------------------------------------------------
# PyMySQL is synchronous, so every call runs in FastAPI's threadpool — the same
# arrangement as services/db.py, and for the same reason: one blocking driver is
# a smaller dependency surface than a second async one.


async def create_chat(chat_id: str | None = None) -> dict:
    """Create a chat, or return the existing one with that id."""
    return await run_in_threadpool(_create_chat_sync, chat_id)


async def list_chats(limit: int = DEFAULT_CHAT_LIMIT) -> list[dict]:
    """Chats by last activity, newest first, with each one's turn count."""
    return await run_in_threadpool(_list_chats_sync, limit)


async def get_chat(chat_id: str) -> dict | None:
    """One chat, or None if it does not exist."""
    return await run_in_threadpool(_get_chat_sync, chat_id)


async def rename_chat(chat_id: str, title: str) -> dict:
    """Retitle a chat. Raises ChatNotFound if it is gone."""
    return await run_in_threadpool(_rename_chat_sync, chat_id, title)


async def delete_chat(chat_id: str) -> bool:
    """Delete a chat and its turns. False if there was nothing to delete."""
    return await run_in_threadpool(_delete_chat_sync, chat_id)


async def append_turn(
    chat_id: str,
    question: str,
    sql: str,
    answer: str,
    table_names: list[str],
) -> dict:
    """Record a completed exchange and bump the chat's last-activity time.

    Raises ChatNotFound if the chat was deleted while the answer was being
    written, which is a normal outcome once chats stream concurrently.
    """
    return await run_in_threadpool(
        _append_turn_sync, chat_id, question, sql, answer, table_names
    )


async def load_history(chat_id: str, limit: int | None = None) -> list[dict]:
    """This chat's turns in order, in HistoryTurn's shape.

    Capped at CONTEXT_MAX_TURNS by default — the same abuse rail that used to
    bound the transcript the browser replayed. The token budget in
    services/context.py is still what decides how much of this the model
    actually sees, and it binds first.
    """
    if limit is None:
        limit = CONTEXT_MAX_TURNS
    if limit <= 0:
        return []
    return await run_in_threadpool(_load_history_sync, chat_id, limit)
